-- Script para adicionar coluna de último usuário que acessou o manual
-- Execute no Oracle

ALTER TABLE TIRF_MANUAIS ADD ID_ULTIMO_ACESSO NUMBER;
ALTER TABLE TIRF_MANUAIS ADD CONSTRAINT FK_MANUAL_ULTIMO_ACESSO FOREIGN KEY (ID_ULTIMO_ACESSO) REFERENCES TIRF_USUARIOS(ID_USUARIO);

COMMIT;
