-- ============================================
-- Tabela de relacionamento Usuário-Loja
-- Permite que um usuário tenha acesso a múltiplas lojas
-- ============================================

-- Criar tabela de relacionamento
CREATE TABLE TIRF_USUARIO_LOJAS (
    ID_USUARIO_LOJA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_USUARIO NUMBER NOT NULL,
    ID_LOJA NUMBER NOT NULL,
    DATA_ATRIBUICAO DATE DEFAULT SYSDATE,
    CONSTRAINT FK_USUARIO_LOJAS_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TIRF_USUARIOS(ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK_USUARIO_LOJAS_LOJA FOREIGN KEY (ID_LOJA) REFERENCES TIRF_LOJAS(ID_LOJA) ON DELETE CASCADE,
    CONSTRAINT UQ_USUARIO_LOJA UNIQUE (ID_USUARIO, ID_LOJA)
);

-- Criar índices para performance
CREATE INDEX IDX_USUARIO_LOJAS_USUARIO ON TIRF_USUARIO_LOJAS(ID_USUARIO);
CREATE INDEX IDX_USUARIO_LOJAS_LOJA ON TIRF_USUARIO_LOJAS(ID_LOJA);

-- Migrar dados existentes de ID_LOJA em TIRF_USUARIOS para a nova tabela
-- (Somente usuários que já têm uma loja associada)
INSERT INTO TIRF_USUARIO_LOJAS (ID_USUARIO, ID_LOJA)
SELECT ID_USUARIO, ID_LOJA 
FROM TIRF_USUARIOS 
WHERE ID_LOJA IS NOT NULL;

-- Comentário: O campo ID_LOJA em TIRF_USUARIOS pode ser mantido por compatibilidade
-- ou removido após confirmação que a migração funcionou
-- Para remover: ALTER TABLE TIRF_USUARIOS DROP COLUMN ID_LOJA;
