-- ============================================
-- Fort Manuais - Script de Inserção de Aplicações
-- Execute este script no Oracle após criar as tabelas
-- ============================================

-- Aplicações do módulo Cadastro
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Cadastro'), 'Cadastro');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Cadastro'), 'Cliente');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Cadastro'), 'Pessoa');

-- Aplicações do módulo Comercial
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Comercial'), 'Acordos E Verbas');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Comercial'), 'Compras');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Comercial'), 'Contrato Fidelidade');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Comercial'), 'Cotação Atacadista');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Comercial'), 'Estoque');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Comercial'), 'Expedição');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Comercial'), 'Gerencial');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Comercial'), 'Inventário');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Comercial'), 'Loja');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Comercial'), 'Parâmetros');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Comercial'), 'Preço');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Comercial'), 'Recebimento');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Comercial'), 'Terminal De Retaguarda');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Comercial'), 'Venda Balcão');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Comercial'), 'Vendas');

-- Aplicações do módulo Financeiro
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Financeiro'), 'Acerto De Carga');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Financeiro'), 'Operador');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Financeiro'), 'Integração Erp');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Financeiro'), 'Orçamento');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Financeiro'), 'Supervisor');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Financeiro'), 'Tesouraria');

-- Aplicações do módulo Contabilidade
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Contabilidade'), 'Contábil');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Contabilidade'), 'Fiscal');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Contabilidade'), 'Patrimonio');

-- Aplicações do módulo Logística
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Logística'), 'Parâmetro');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Logística'), 'Logística');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Logística'), 'Portaria');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Logística'), 'Produtividade');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Logística'), 'Route');
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Logística'), 'Transporte');

-- Aplicações do módulo Transportadora
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Transportadora'), 'Transportadora');

-- Aplicações do módulo Atendimento Sac
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Atendimento Sac'), 'Atendimento Sac');

-- Aplicações do módulo Segurança
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Segurança'), 'Segurança');

-- Aplicações do módulo Web
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Web'), 'Web');

-- Aplicações do módulo NF-E
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'NF-E'), 'NF-E');

-- Aplicações do módulo Totvs
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Totvs'), 'Totvs');

-- Aplicações do módulo Utilitários
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Utilitários'), 'Utilitários');

-- Aplicações do módulo Consultas
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Consultas'), 'Consultas');

-- Aplicações do módulo Meus Dashboards
INSERT INTO TIRF_APLICACOES (ID_MODULO, NOME_APLICACAO) VALUES ((SELECT ID_MODULO FROM TIRF_MODULOS WHERE NOME_MODULO = 'Meus Dashboards'), 'Meus Dashboards');

COMMIT;
