-- Adicionar suporte a PDF na tabela de Manuais
ALTER TABLE TIRF_MANUAIS ADD ARQUIVO_PDF VARCHAR2(255);
ALTER TABLE TIRF_MANUAIS ADD TIPO_CONTEUDO VARCHAR2(10) DEFAULT 'HTML' CHECK (TIPO_CONTEUDO IN ('HTML', 'PDF'));
COMMIT;
