-- ============================================
-- Fort Manuais de Processos - Migration Lojas (Per-Store Tables)
-- Banco de Dados: Oracle Database
-- ============================================

-- 1. Criação da Tabela Mestra de Lojas (Referência)
-- Tenta criar apenas se não existir (O tratamento de erro deve ser feito na execução ou manualmente)
DECLARE
  v_count NUMBER;
BEGIN
  SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'TIRF_LOJAS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE TIRF_LOJAS (
        ID_LOJA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        NUMERO_LOJA VARCHAR2(10) NOT NULL UNIQUE,
        NOME_LOJA VARCHAR2(150) NOT NULL,
        STATUS VARCHAR2(20) DEFAULT ''ATIVO'' CHECK (STATUS IN (''ATIVO'', ''INATIVO'')),
        DATA_CRIACAO DATE DEFAULT SYSDATE
    )';

  END IF;
END;
/

-- 2. Script para criar tabelas específicas de cada loja (2 a 50) e atualizar Roles de usuário

DECLARE
    v_suffix VARCHAR2(10);
    v_sql CLOB;
    v_roles CLOB := '''TI'', ''COLABORADOR'', ''LEITOR''';
    v_constraint_name VARCHAR2(100);
BEGIN
    -- Loop para criar tabelas das lojas 2 a 50
    FOR i IN 2..50 LOOP
        -- Pular lojas excluídas: 04, 22, 34, 38, 43, 45
        IF i IN (4, 22, 34, 38, 43, 45) THEN
            CONTINUE;
        END IF;

        -- Formatar sufixo: LOJA02, LOJA03, ...
        v_suffix := 'LOJA' || LPAD(i, 2, '0');
        
        -- Adicionar role à lista acumulada para a constraint de usuários
        v_roles := v_roles || ', ''' || v_suffix || '''';
        
        DBMS_OUTPUT.PUT_LINE('Processando tabelas para: ' || v_suffix);

        -- Inserir registro na tabela mestra de Lojas (Opcional, para manter consistência)
        BEGIN
            EXECUTE IMMEDIATE 'INSERT INTO TIRF_LOJAS (NUMERO_LOJA, NOME_LOJA) VALUES (:1, :2)' 
            USING LPAD(i, 2, '0'), 'Loja ' || LPAD(i, 2, '0');
        EXCEPTION
            WHEN DUP_VAL_ON_INDEX THEN NULL; -- Ignora se já existe
        END;

        -- A. Tabela de Módulos (Específica da Loja)
        BEGIN
            v_sql := 'CREATE TABLE TIRF_MODULOS_' || v_suffix || ' (
                ID_MODULO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NOME_MODULO VARCHAR2(100) NOT NULL,
                ICONE VARCHAR2(50)
            )';
            EXECUTE IMMEDIATE v_sql;
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF; -- Ignora erro se tabela já existe
        END;

        -- B. Tabela de Aplicações (Específica da Loja)
        BEGIN
            v_sql := 'CREATE TABLE TIRF_APLICACOES_' || v_suffix || ' (
                ID_APLICACAO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ID_MODULO NUMBER NOT NULL,
                NOME_APLICACAO VARCHAR2(150) NOT NULL,
                CONSTRAINT FK_APP_MODULO_' || v_suffix || ' FOREIGN KEY (ID_MODULO) REFERENCES TIRF_MODULOS_' || v_suffix || '(ID_MODULO)
            )';
            EXECUTE IMMEDIATE v_sql;
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
        END;

        -- C. Tabela de Manuais (Específica da Loja)
        -- Referencia as tabelas locais de Modulo/App, mas Usuarios globais
        BEGIN
            v_sql := 'CREATE TABLE TIRF_MANUAIS_' || v_suffix || ' (
                ID_MANUAL NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ID_APLICACAO NUMBER NOT NULL,
                ID_AUTOR NUMBER NOT NULL,
                ID_ULTIMO_ACESSO NUMBER,
                ID_ULTIMO_EDITOR NUMBER,
                TITULO VARCHAR2(200) NOT NULL,
                DESCRICAO_CARD VARCHAR2(400),
                CONTEUDO_HTML CLOB,
                QTD_VIEWS NUMBER DEFAULT 0,
                STATUS VARCHAR2(20) DEFAULT ''ATIVO'' CHECK (STATUS IN (''ATIVO'', ''LIXEIRA'')),
                DATA_CRIACAO DATE DEFAULT SYSDATE,
                DATA_ATUALIZACAO DATE DEFAULT SYSDATE,
                CONSTRAINT FK_MANUAL_APP_' || v_suffix || ' FOREIGN KEY (ID_APLICACAO) REFERENCES TIRF_APLICACOES_' || v_suffix || '(ID_APLICACAO),
                CONSTRAINT FK_MANUAL_AUTOR_' || v_suffix || ' FOREIGN KEY (ID_AUTOR) REFERENCES TIRF_USUARIOS(ID_USUARIO),
                CONSTRAINT FK_MANUAL_U_ACESSO_' || v_suffix || ' FOREIGN KEY (ID_ULTIMO_ACESSO) REFERENCES TIRF_USUARIOS(ID_USUARIO),
                CONSTRAINT FK_MANUAL_U_EDITOR_' || v_suffix || ' FOREIGN KEY (ID_ULTIMO_EDITOR) REFERENCES TIRF_USUARIOS(ID_USUARIO)
            )';
            EXECUTE IMMEDIATE v_sql;
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
        END;

        -- D. Índices
        BEGIN
            EXECUTE IMMEDIATE 'CREATE INDEX IDX_MANUAIS_APP_' || v_suffix || ' ON TIRF_MANUAIS_' || v_suffix || '(ID_APLICACAO)';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;

    END LOOP;

    -- 3. Atualizar Tabela de Usuários (Implementar LojaX como Cargo)
    
    DBMS_OUTPUT.PUT_LINE('Atualizando permissões de usuário...');

    -- Tentar identificar e dropar a constraint de CK do PERFIL
    -- Nota: Isso busca qualquer CHECK constraint na coluna PERFIL. 
    -- Se houver múltiplas ou nomes complexos, pode precisar de ajuste.
    FOR r IN (SELECT CONSTRAINT_NAME FROM USER_CONS_COLUMNS WHERE TABLE_NAME = 'TIRF_USUARIOS' AND COLUMN_NAME = 'PERFIL') LOOP
        BEGIN
             -- Check se é constraint de CHECK (search_condition is not null na user_constraints)
             -- Simplificação: tenta dropar direto
             EXECUTE IMMEDIATE 'ALTER TABLE TIRF_USUARIOS DROP CONSTRAINT ' || r.CONSTRAINT_NAME;
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    -- Criar nova constraint com todas as roles geradas + padroes
    v_sql := 'ALTER TABLE TIRF_USUARIOS ADD CONSTRAINT CHK_USUARIO_PERFIL CHECK (PERFIL IN (' || v_roles || '))';
    EXECUTE IMMEDIATE v_sql;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Migração concluída com sucesso.');
END;
/
