-- Generated Replication Script


INSERT INTO TIRF_MODULOS_LOJA02 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA02 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA02 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA02 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA03 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA03 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA03 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA03 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA05 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA05 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA05 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA05 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA06 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA06 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA06 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA06 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA07 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA07 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA07 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA07 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA08 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA08 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA08 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA08 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA09 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA09 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA09 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA09 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA10 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA10 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA10 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA10 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA11 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA11 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA11 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA11 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA12 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA12 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA12 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA12 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA13 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA13 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA13 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA13 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA14 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA14 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA14 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA14 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA15 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA15 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA15 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA15 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA16 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA16 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA16 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA16 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA17 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA17 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA17 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA17 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA18 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA18 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA18 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA18 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA19 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA19 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA19 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA19 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA20 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA20 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA20 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA20 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA21 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA21 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA21 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA21 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA23 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA23 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA23 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA23 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA24 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA24 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA24 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA24 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA25 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA25 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA25 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA25 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA26 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA26 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA26 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA26 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA27 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA27 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA27 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA27 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA28 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA28 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA28 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA28 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA29 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA29 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA29 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA29 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA30 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA30 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA30 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA30 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA31 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA31 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA31 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA31 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA32 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA32 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA32 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA32 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA33 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA33 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA33 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA33 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA35 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA35 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA35 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA35 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA36 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA36 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA36 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA36 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA37 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA37 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA37 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA37 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA39 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA39 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA39 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA39 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA40 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA40 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA40 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA40 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA41 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA41 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA41 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA41 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA42 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA42 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA42 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA42 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA44 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA44 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA44 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA44 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA46 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA46 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA46 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA46 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA47 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA47 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA47 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA47 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA48 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA48 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA48 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA48 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA49 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA49 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA49 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA49 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MODULOS_LOJA50 (ID_MODULO, NOME_MODULO, ICONE)
SELECT ID_MODULO, NOME_MODULO, ICONE FROM TIRF_MODULOS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MODULOS_LOJA50 tm WHERE tm.ID_MODULO = m.ID_MODULO);

INSERT INTO TIRF_APLICACOES_LOJA50 (ID_APLICACAO, ID_MODULO, NOME_APLICACAO)
SELECT ID_APLICACAO, ID_MODULO, NOME_APLICACAO FROM TIRF_APLICACOES a
WHERE NOT EXISTS (SELECT 1 FROM TIRF_APLICACOES_LOJA50 ta WHERE ta.ID_APLICACAO = a.ID_APLICACAO);

INSERT INTO TIRF_MANUAIS_LOJA33 (
    ID_MANUAL, ID_APLICACAO, ID_AUTOR, ID_ULTIMO_ACESSO, ID_ULTIMO_EDITOR, 
    TITULO, DESCRICAO_CARD, CONTEUDO_HTML, QTD_VIEWS, STATUS, 
    DATA_CRIACAO, DATA_ATUALIZACAO
)
SELECT 
    ID_MANUAL, ID_APLICACAO, ID_AUTOR, ID_ULTIMO_ACESSO, ID_ULTIMO_EDITOR, 
    TITULO, DESCRICAO_CARD, CONTEUDO_HTML, QTD_VIEWS, STATUS, 
    DATA_CRIACAO, DATA_ATUALIZACAO
FROM TIRF_MANUAIS m
WHERE NOT EXISTS (SELECT 1 FROM TIRF_MANUAIS_LOJA33 tm WHERE tm.ID_MANUAL = m.ID_MANUAL);

COMMIT;
