const oracledb = require('oracledb');
require('dotenv').config();

async function migrate() {
    let connection;
    try {
        // Inicializar Oracle Client
        try {
            oracledb.initOracleClient({ libDir: 'C:\\instantclient_23_0' });
            console.log('✅ Oracle Instant Client inicializado');
        } catch (err) {
            if (!err.message.includes('already been initialized')) {
                throw err;
            }
        }

        connection = await oracledb.getConnection({
            user: process.env.DB_USER,
            password: process.env.DB_PASSWORD,
            connectString: process.env.DB_CONNECTION_STRING
        });

        console.log('✅ Conectado ao banco de dados');

        // Criar tabela TIRF_USUARIO_LOJAS
        try {
            await connection.execute(`
                CREATE TABLE TIRF_USUARIO_LOJAS (
                    ID_USUARIO_LOJA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ID_USUARIO NUMBER NOT NULL,
                    ID_LOJA NUMBER NOT NULL,
                    DATA_ATRIBUICAO DATE DEFAULT SYSDATE,
                    CONSTRAINT FK_USUARIO_LOJAS_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TIRF_USUARIOS(ID_USUARIO) ON DELETE CASCADE,
                    CONSTRAINT FK_USUARIO_LOJAS_LOJA FOREIGN KEY (ID_LOJA) REFERENCES TIRF_LOJAS(ID_LOJA) ON DELETE CASCADE,
                    CONSTRAINT UQ_USUARIO_LOJA UNIQUE (ID_USUARIO, ID_LOJA)
                )
            `);
            console.log('✅ Tabela TIRF_USUARIO_LOJAS criada');
        } catch (err) {
            if (err.message.includes('ORA-00955')) {
                console.log('ℹ️ Tabela TIRF_USUARIO_LOJAS já existe');
            } else {
                throw err;
            }
        }

        // Criar índices
        try {
            await connection.execute(`
                CREATE INDEX IDX_USUARIO_LOJAS_USUARIO ON TIRF_USUARIO_LOJAS(ID_USUARIO)
            `);
            console.log('✅ Índice IDX_USUARIO_LOJAS_USUARIO criado');
        } catch (err) {
            if (err.message.includes('ORA-00955')) {
                console.log('ℹ️ Índice IDX_USUARIO_LOJAS_USUARIO já existe');
            } else {
                console.log('⚠️ Erro ao criar índice:', err.message);
            }
        }

        try {
            await connection.execute(`
                CREATE INDEX IDX_USUARIO_LOJAS_LOJA ON TIRF_USUARIO_LOJAS(ID_LOJA)
            `);
            console.log('✅ Índice IDX_USUARIO_LOJAS_LOJA criado');
        } catch (err) {
            if (err.message.includes('ORA-00955')) {
                console.log('ℹ️ Índice IDX_USUARIO_LOJAS_LOJA já existe');
            } else {
                console.log('⚠️ Erro ao criar índice:', err.message);
            }
        }

        // Migrar dados existentes de ID_LOJA em TIRF_USUARIOS para a nova tabela
        const result = await connection.execute(`
            INSERT INTO TIRF_USUARIO_LOJAS (ID_USUARIO, ID_LOJA)
            SELECT ID_USUARIO, ID_LOJA 
            FROM TIRF_USUARIOS 
            WHERE ID_LOJA IS NOT NULL
            AND NOT EXISTS (
                SELECT 1 FROM TIRF_USUARIO_LOJAS ul 
                WHERE ul.ID_USUARIO = TIRF_USUARIOS.ID_USUARIO 
                AND ul.ID_LOJA = TIRF_USUARIOS.ID_LOJA
            )
        `);
        console.log(`✅ Migrados ${result.rowsAffected} usuários com lojas associadas`);

        await connection.commit();
        console.log('✅ Migração concluída com sucesso!');

    } catch (error) {
        console.error('❌ Erro na migração:', error);
        if (connection) {
            await connection.rollback();
        }
        process.exit(1);
    } finally {
        if (connection) {
            await connection.close();
        }
    }
}

migrate();
